insert into memtype values('CH','CHILD',39.95)
insert into memtype values('ST','STUDENT',49.95)
insert into memtype values('AD','ADULT',54.95)
insert into memtype values('SR','SENIOR',44.95)
insert into memtype values('FM','FAMILY',74.95)
